### PR TITLE
remove old versions

### PR DESCRIPTION
**Pull request by dallman2**
Hey, I was mistaken with my previous update. My existing build was able to run, but could not complete dependancy resolution from scratch. I have removed the issues.

### CODE REVIEW

**Comment by gadicc** [comment]
Thanks, @dallman2.  I must admit, I haven't really touched Meteor in years, but won't this then break the package for everyone on an earlier version?

If that's the only way get it working with v3, I can do a major version bump to keep semver compatibility.  But it would be great if there's someway to have one version of the package that works for all meteor versions?

**Comment by dallman2** [comment]
@gadicc you raise a good point, a change like that could break very old projects. I think a major version bump would be a good solution for now. I am not totally sure if there is a solution that keeps everything working on one version, as Meteor's dependancy resolution system is somewhat mysterious to me. 

As a matter of context, the version of Node that comes bundled with Meteor versions 2.14 and below will stop receiving security updates this April. Hopefully, many projects on Meteor 2.x and even 1.x will migrate to avoid the security headache:)

In the meantime, I think this change with a major version bump would be a good for now.

**Comment by gadicc** [comment]
Sounds good, thanks!  Going to go ahead with this :pray:

**Comment by gadicc** [comment]
Oops, ref'd #29 in the commit message of the v2 publish, so here it is for reference: 

https://github.com/gadicc/meteor-blaze-react-component/commit/430a652616888d7f8d174b5e5df8a146857e4245

**Pull request merged**
